package me.erriic.ffaaddon;

public enum ListEditOperation {
  ADD_ALLY_PLAYER, ADD_ENEMY_PLAYER, ADD_ALLY_CLAN, ADD_ENEMY_CLAN, REMOVE_ALLY_PLAYER, REMOVE_ENEMY_PLAYER, REMOVE_ALLY_CLAN, REMOVE_ENEMY_CLAN
}

